name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Format, lint, type check
        run: |
          uv run poe format
          uv run poe lint
          uv run poe lint-types

      - name: Run tests
        run: |
          uv run pytest
